import React,{useEffect,useMemo,useState} from 'react';
import AdminLayout from '../../layouts/AdminLayout.jsx';
import {getAdminMonthlySettings,saveAdminSeasonality} from '../../services/adminMonthlySettingsService.js';
import './AdminSettingsPage.css';
const MONTHS=['Janvier','Février','Mars','Avril','Mai','Juin','Juillet','Août','Septembre','Octobre','Novembre','Décembre'];
const OPTIONS=[['unknown','Inconnue'],['low','Faible'],['normal','Normale'],['high','Forte']];
const fmt=n=>n===null||n===undefined||!Number.isFinite(Number(n))?'—':new Intl.NumberFormat('fr-FR',{maximumFractionDigits:1}).format(n);
function delta(v){if(v===null||v===undefined||!Number.isFinite(Number(v)))return '—';return (v>0?'+':'')+new Intl.NumberFormat('fr-FR',{style:'percent',maximumFractionDigits:1}).format(v)}
function monthNow(){return new Intl.DateTimeFormat('en-CA',{timeZone:'Europe/Paris',year:'numeric',month:'2-digit'}).format(new Date())}
const DEFAULT=Array(12).fill('unknown');
export default function AdminSettingsPage(){
 const [month,setMonth]=useState(monthNow),[query,setQuery]=useState(''),[quality,setQuality]=useState('all');
 const [tab,setTab]=useState('results'),[data,setData]=useState(null),[loading,setLoading]=useState(false),[error,setError]=useState('');
 const [seasons,setSeasons]=useState(DEFAULT),[reason,setReason]=useState(''),[version,setVersion]=useState(0),[saveState,setSaveState]=useState('');
 useEffect(()=>{let active=true;setLoading(true);setError('');setData(null);getAdminMonthlySettings(month).then(r=>{if(!active)return;setData(r);setSeasons(r.seasonality.months);setReason(r.seasonality.reason||'');setVersion(r.seasonality.version)}).catch(e=>{if(active)setError(e.message)}).finally(()=>{if(active)setLoading(false)});return()=>{active=false}},[month]);
 const rows=useMemo(()=>{const value=query.trim().toLowerCase();return (data?.departments||[]).filter(r=>(!value||r.departmentCode.toLowerCase().includes(value))&&(quality==='all'||r.quality===quality))},[data,query,quality]);
 async function save(){setSaveState('Enregistrement…');try{const r=await saveAdminSeasonality(seasons,reason,version);setVersion(r.version);setSaveState('Saisonnalité enregistrée, sans effet sur les vigilances publiées.')}catch(e){setSaveState(e.message)}}
 return <AdminLayout>
  <section className="admin-console-page-head"><div><p className="admin-console-eyebrow">Pilotage et méthode</p><h1>Paramétrage</h1><p>Critères territoriaux, saisonnalité déclarée et comparaisons mensuelles vérifiables.</p></div></section>
  <nav className="settings-tabs" aria-label="Sections paramétrage"><button type="button" className={tab==='results'?'active':''} onClick={()=>setTab('results')}>Résultats mensuels</button><button type="button" className={tab==='seasonality'?'active':''} onClick={()=>setTab('seasonality')}>Saisonnalité</button><button type="button" className={tab==='method'?'active':''} onClick={()=>setTab('method')}>Critères & méthode</button></nav>
  <section className="panel settings-filters"><label>Mois analysé<input type="month" value={month} max={monthNow()} onChange={e=>setMonth(e.target.value)}/></label><div className="settings-note">Comparaison M−1 : mois précédent · M−12 : même mois un an avant. Les périodes indisponibles restent vides.</div></section>
  {loading?<section className="panel" role="status">Lecture des relevés mensuels et des références INSEE…</section>:null}
  {error?<section className="admin-console-alert admin-console-alert-error" role="alert">{error}. Aucun chiffre n'a été inventé.</section>:null}
  {data&&tab==='results'?<><section className="panel"><div className="section-heading"><div><p className="kicker">Observation mensuelle</p><h2>Résultats par département</h2></div><span className="soft-pill">{rows.length} département(s)</span></div><div className="settings-controls"><label>Filtrer par code<input type="search" value={query} onChange={e=>setQuery(e.target.value)} placeholder="72, 75, 2A…"/></label><label>Fiabilité<select value={quality} onChange={e=>setQuality(e.target.value)}><option value="all">Tous les états</option><option value="comparable">Comparable</option><option value="indicative">Indicatif</option><option value="incomplete">Incomplet</option><option value="saturated">Plafonnement suspecté</option><option value="method_change">Méthode différente</option></select></label></div>
  <div className="table-wrapper settings-table-scroll"><table className="simple-table settings-table"><thead><tr><th scope="col">Dépt.</th><th scope="col">Jours relevés</th><th scope="col">Offres moy./j</th><th scope="col">Postes moy./j</th><th scope="col">15–29 ans</th><th scope="col">Employeurs INSEE</th><th scope="col">Offres/10 000 jeunes</th><th scope="col">Offres/100 employeurs</th><th scope="col">M−1</th><th scope="col">M−12</th><th scope="col">Fiabilité</th></tr></thead><tbody>{rows.map(r=><tr key={r.departmentCode}><th scope="row">{r.departmentCode}</th><td>{r.daysObserved}/{r.daysExpected}</td><td>{fmt(r.averageOffers)}</td><td>{fmt(r.averageOpenings)}</td><td>{fmt(r.population15To29)}</td><td>{fmt(r.activeEmployerEstablishmentsCount)}</td><td><strong>{fmt(r.offersPer10000Young)}</strong></td><td>{fmt(r.offersPer100Employers)}</td><td>{delta(r.changeMonth)}</td><td>{delta(r.changeYear)}</td><td><span className={'settings-quality settings-quality-'+r.quality}>{({comparable:'Comparable',indicative:'Indicatif',incomplete:'Incomplet',saturated:'Plafonnement suspecté',method_change:'Rupture de méthode'})[r.quality]||r.quality}</span></td></tr>)}</tbody></table></div><p className="date-line">« — » signifie que la donnée ou la comparaison fiable est indisponible. Les ratios utilisent les stocks quotidiens moyens, pas le total des annonces accumulées pendant le mois.</p></section></>:null}
  {data&&tab==='seasonality'?<section className="panel"><div className="section-heading"><div><p className="kicker">Configuration humaine</p><h2>Calendrier saisonnier national</h2></div><span className="soft-pill">Version {version}</span></div><p className="date-line">Ces catégories sont des hypothèses administratives. Elles ne modifient ni la collecte ni les couleurs de vigilance.</p><div className="settings-season-grid">{MONTHS.map((label,i)=><label key={label}>{label}<select value={seasons[i]} onChange={e=>setSeasons(old=>old.map((v,j)=>i===j?e.target.value:v))}>{OPTIONS.map(([v,t])=><option value={v} key={v}>{t}</option>)}</select></label>)}</div><label className="settings-reason">Justification documentée<textarea rows="3" value={reason} onChange={e=>setReason(e.target.value)} maxLength={1000} placeholder="Source, contexte, motif de la modification (10 caractères minimum)"/></label><div className="settings-save"><button type="button" className="admin-detail-button" onClick={save} disabled={reason.trim().length<10}>Enregistrer une nouvelle version</button><span role="status">{saveState}</span></div></section>:null}
  {tab==='method'?<section className="panel settings-method"><h2>Critères retenus</h2><div className="settings-method-grid"><article><strong>Offres observées</strong><p>Moyenne des stocks quotidiens stricts et géolocalisés dans le département.</p></article><article><strong>Postes observés</strong><p>Moyenne du nombre de postes ouverts sur les mêmes journées.</p></article><article><strong>Population</strong><p>Résidents de 15 à 29 ans, référence INSEE {data?.populationReferenceYear||'non disponible'}.</p></article><article><strong>Employeurs</strong><p>Établissements actifs employeurs Sirene, uniquement lorsque l'import départemental et les agrégats NAF sont complets.</p></article><article><strong>Ratio principal</strong><p>Offres actives moyennes ÷ population jeune × 10 000.</p></article><article><strong>Variations M−1 / M−12</strong><p>Variation relative du ratio principal à périmètre et dénominateur comparables. Pas de variation lorsque la référence vaut zéro.</p></article><article><strong>Saisonnalité</strong><p>Hypothèse humaine révisable, non interprétée comme une correction statistique du ratio.</p></article><article><strong>Fiabilité</strong><p>Mois complets, méthodes cohérentes, contrôle du plafonnement. Une période partielle ne fonde pas une comparaison mensuelle.</p></article></div></section>:null}
 </AdminLayout>
}